import { useEffect, useMemo, useRef, useState } from "react";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BrowserRouter, MemoryRouter, NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Placeholder from "@tiptap/extension-placeholder";
import { Background, Controls, ReactFlow, type Edge, type Node } from "@xyflow/react";
import cytoscape from "cytoscape";
import type { BookRecord, GraphData, StudioDataSource } from "../shared/index.js";

const queryClient = new QueryClient({ defaultOptions: { queries: { staleTime: 2_000, retry: 1 } } });
const nav = [
  ["/", "Overview", "01"], ["/setup", "New project", "02"], ["/editor", "Manuscript", "03"],
  ["/graph", "Story graph", "04"], ["/workflow", "DAG control", "05"], ["/reviews", "Review center", "06"], ["/exports", "Exports", "07"],
] as const;

function Icon({ name }: { name: string }) { return <span className="icon" aria-hidden="true">{name}</span>; }

function Frame({ source }: { source: StudioDataSource }) {
  const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: () => source.dashboard() });
  const firstBook = dashboard.data?.books[0];
  const [palette, setPalette] = useState(false);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setPalette((value) => !value); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  return <div className="studio-shell">
    <aside className="rail">
      <a className="brand" href="/"><span className="brand-mark">I/O</span><span><b>InkOS</b><small>STUDIO / ALPHA</small></span></a>
      <nav aria-label="Studio navigation">{nav.map(([to, label, number]) => <NavLink key={to} end={to === "/"} to={to}><span>{number}</span>{label}</NavLink>)}</nav>
      <div className="rail-status"><span className="signal verified" />LOCAL ONLY<small>{source.mode === "demo" ? "Fixture mode" : "SQLite connected"}</small></div>
    </aside>
    <main className="workspace">
      <header className="topbar"><div className="breadcrumbs"><span>INKOS</span><i>/</i><b>{firstBook?.title ?? "UNCONFIGURED"}</b></div><button className="command" onClick={() => setPalette(true)}>Search or command <kbd>⌘ K</kbd></button><span className="privacy"><span className="signal verified" /> PRIVATE WORKSPACE</span></header>
      <Routes>
        <Route path="/" element={<Dashboard source={source} />} />
        <Route path="/setup" element={<Setup source={source} />} />
        <Route path="/editor" element={firstBook ? <Navigate to={`/editor/${firstBook.id}`} replace /> : <Navigate to="/setup" replace />} />
        <Route path="/editor/:bookId" element={<Editor source={source} />} />
        <Route path="/graph" element={firstBook ? <GraphView source={source} book={firstBook} /> : <Empty />} />
        <Route path="/workflow" element={firstBook ? <Workflow source={source} book={firstBook} /> : <Empty />} />
        <Route path="/reviews" element={firstBook ? <Reviews source={source} book={firstBook} /> : <Empty />} />
        <Route path="/exports" element={firstBook ? <Exports source={source} book={firstBook} /> : <Empty />} />
      </Routes>
    </main>
    {palette && <div className="modal-backdrop" onClick={() => setPalette(false)}><div className="palette" role="dialog" aria-modal="true" aria-label="Command palette" onClick={(event) => event.stopPropagation()}><input autoFocus placeholder="Type a command…"/><p>JUMP TO</p>{nav.map(([to, label]) => <a href={`#${to}`} key={to}>{label}<span>↵</span></a>)}</div></div>}
  </div>;
}

function PageHeader({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div>{action}</div>; }
function Empty() { return <section className="page"><PageHeader eyebrow="NO PROJECT" title="Create a project first." detail="A series and book establish the graph, revision history, and workflow boundaries."/><NavLink className="button primary" to="/setup">Configure project</NavLink></section>; }

function Dashboard({ source }: { source: StudioDataSource }) {
  const data = useQuery({ queryKey: ["dashboard"], queryFn: () => source.dashboard() });
  if (data.isLoading) return <section className="page"><p className="eyebrow">SYNCHRONIZING LOCAL STATE…</p></section>;
  if (data.error) return <section className="page"><div className="notice blocked">Could not load Studio: {data.error.message}</div></section>;
  const d = data.data!; const spend = d.jobs.reduce((total, job) => total + job.used_cents, 0);
  return <section className="page"><PageHeader eyebrow="AUTHORING CONTROL ROOM" title="Production overview" detail="Every draft, state transition, review, and gate remains inspectable." action={<NavLink className="button primary" to="/setup">+ New project</NavLink>}/>
    {source.mode === "demo" && <div className="notice attention"><b>INTERACTIVE FIXTURE</b> Changes remain in this browser session. No model calls, credentials, or manuscript data are used.</div>}
    <div className="metric-grid"><Metric label="BOOKS" value={String(d.books.length).padStart(2,"0")} note="Active production"/><Metric label="OPEN HARD GATES" value={String(d.obligations.filter((o) => o.hard).length).padStart(2,"0")} note="Must resolve or waive" tone="attention"/><Metric label="ACTIVE JOBS" value={String(d.jobs.filter((j) => ["running","blocked"].includes(j.status)).length).padStart(2,"0")} note="Durable and resumable"/><Metric label="RUN COST" value={`$${(spend/100).toFixed(2)}`} note="Current local ledger"/></div>
    <div className="dashboard-grid"><article className="panel span-2"><PanelTitle index="A" title="PRODUCTION QUEUE"/><div className="table-head"><span>BOOK / SERIES</span><span>GENRE</span><span>STATUS</span><span /></div>{d.books.map((book) => <NavLink className="table-row" to={`/editor/${book.id}`} key={book.id}><span><b>{book.title}</b><small>{book.series_title}</small></span><code>{book.genre_pack}</code><span className="status"><i className="signal active"/>DRAFTING</span><span>OPEN →</span></NavLink>)}{!d.books.length && <p className="empty-copy">No books yet. Configure the first production project.</p>}</article>
      <article className="panel"><PanelTitle index="B" title="HARD OBLIGATIONS"/><div className="obligation-list">{d.obligations.slice(0,5).map((item) => <div key={item.id}><span className={`signal ${item.status === "open" ? "blocked" : "attention"}`}/><span><b>{item.title}</b><small>{item.kind} · {item.status}</small></span></div>)}{!d.obligations.length && <p className="empty-copy">No unresolved hard gates.</p>}</div></article>
      <article className="panel span-3"><PanelTitle index="C" title="RECENT ATTRIBUTABLE EVENTS"/><div className="event-strip">{d.recentEvents.map((event) => <div key={event.id}><code>{event.event_type}</code><p>{event.rationale}</p><time>{new Date(event.created_at).toLocaleString()}</time></div>)}{!d.recentEvents.length && <p className="empty-copy">Events appear as authors and agents modify the project.</p>}</div></article></div>
  </section>;
}
function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone?: string }) { return <article className={`metric ${tone ?? ""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function PanelTitle({ index, title }: { index: string; title: string }) { return <h2 className="panel-title"><span>{index}</span>{title}</h2>; }

function Setup({ source }: { source: StudioDataSource }) {
  const navigate = useNavigate(); const qc = useQueryClient(); const [telemetry, setTelemetry] = useState(false);
  const mutation = useMutation({ mutationFn: (form: FormData) => source.createProject({ seriesTitle: String(form.get("seriesTitle")), bookTitle: String(form.get("bookTitle")), premise: String(form.get("premise")), genrePack: String(form.get("genrePack")), seedMystery: form.get("seedMystery") === "on" }), onSuccess: async ({ bookId }) => { await qc.invalidateQueries({ queryKey: ["dashboard"] }); navigate(`/editor/${bookId}`); } });
  return <section className="page narrow"><PageHeader eyebrow="PROJECT INITIALIZATION" title="Establish production boundaries" detail="InkOS records these choices as the first attributable canon event."/><form className="setup-grid" onSubmit={(event) => { event.preventDefault(); mutation.mutate(new FormData(event.currentTarget)); }}><label>SERIES TITLE<input name="seriesTitle" required defaultValue="The Calder House Files"/></label><label>BOOK TITLE<input name="bookTitle" required defaultValue="A Clock Without Hands"/></label><label className="wide">PREMISE<textarea name="premise" required defaultValue="A detective discovers that the most reliable witness in a locked-room death is the one thing that made no sound."/></label><label>GENRE PACK<select name="genrePack" defaultValue="mystery"><option value="mystery">Mystery</option><option value="general">General fiction</option><option value="science-fiction">Science fiction</option><option value="romantasy">Romantasy</option></select></label><label>MONTHLY BUDGET<input name="budget" type="number" min="0" defaultValue="25"/></label><label className="toggle wide"><input name="seedMystery" type="checkbox" defaultChecked/><span>Seed the mystery fairness ledger and require a locked solution before drafting</span></label><label className="toggle wide"><input type="checkbox" checked={telemetry} onChange={(e) => setTelemetry(e.target.checked)}/><span>Share anonymous diagnostics. Never includes manuscript text, prompts, paths, or credentials. <a href="https://csandbatch.github.io/inkos/docs/operations/privacy/">Preview fields.</a></span></label><div className="form-actions wide"><button className="button primary" disabled={mutation.isPending}>{mutation.isPending ? "CREATING…" : "CREATE LOCAL PROJECT"}</button>{mutation.error && <span className="error">{mutation.error.message}</span>}</div></form></section>;
}

function Editor({ source }: { source: StudioDataSource }) {
  const { bookId = "" } = useParams(); const qc = useQueryClient(); const data = useQuery({ queryKey: ["book", bookId], queryFn: () => source.book(bookId), enabled: Boolean(bookId) }); const [selected, setSelected] = useState(0); const chapter = data.data?.chapters[selected]; const [saveState, setSaveState] = useState("SAVED");
  const editor = useEditor({ extensions: [StarterKit, Placeholder.configure({ placeholder: "Begin the scene…" })], content: chapter?.content_markdown ?? "", onUpdate: () => setSaveState("UNSAVED") }, [chapter?.id]);
  useEffect(() => { if (editor && chapter && editor.getText() !== chapter.content_markdown) editor.commands.setContent(chapter.content_markdown); }, [editor, chapter]);
  const save = async () => { if (!chapter || !editor) return; setSaveState("SAVING"); await source.saveChapter(chapter.id, { contentMarkdown: editor.getText(), reason: "Studio autosave" }); setSaveState("SAVED"); await qc.invalidateQueries({ queryKey: ["book", bookId] }); };
  useEffect(() => { if (saveState !== "UNSAVED") return; const timer = setTimeout(() => void save(), 1200); return () => clearTimeout(timer); }, [saveState]);
  if (!data.data) return <section className="page"><p className="eyebrow">LOADING MANUSCRIPT…</p></section>;
  return <section className="editor-layout"><aside className="chapter-list"><p className="eyebrow">MANUSCRIPT</p><h2>{data.data.book.title}</h2>{data.data.chapters.map((item, index) => <button className={index === selected ? "selected" : ""} onClick={() => setSelected(index)} key={item.id}><span>{String(item.number).padStart(2,"0")}</span><b>{item.title}</b><small>{item.status}</small></button>)}</aside><article className="manuscript"><div className="editor-toolbar"><button onClick={() => editor?.chain().focus().toggleBold().run()}><b>B</b></button><button onClick={() => editor?.chain().focus().toggleItalic().run()}><i>I</i></button><button onClick={() => editor?.chain().focus().toggleHeading({ level: 2 }).run()}>H2</button><span/><code className={saveState.toLowerCase()}>{saveState}</code><button className="button" onClick={() => void save()}>SAVE REVISION</button></div><div className="chapter-heading"><p>CHAPTER {chapter?.number}</p><input aria-label="Chapter title" value={chapter?.title ?? ""} readOnly/></div><EditorContent editor={editor}/></article><aside className="diagnostics"><PanelTitle index="D" title="DIAGNOSTICS"/><div className="diagnostic blocked"><b>CAUSAL CONTRADICTION</b><p>A witness reports hearing a clock documented as stopped.</p><a href="https://csandbatch.github.io/inkos/docs/guides/review/">Understand this gate →</a></div><PanelTitle index="R" title="REVISIONS"/>{data.data.revisions.slice(0,6).map((revision) => <div className="revision" key={revision.id}><b>{revision.reason}</b><small>{revision.applied_by} · {new Date(revision.created_at).toLocaleTimeString()}</small></div>)}</aside></section>;
}

function GraphCanvas({ graph }: { graph: GraphData }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current) return; const instance = cytoscape({ container: ref.current, elements: [...graph.entities.map((entity) => ({ data: { id: entity.id, label: entity.name, type: entity.type } })), ...graph.edges.map((edge) => ({ data: { id: edge.id, source: edge.from_id, target: edge.to_id, label: edge.type } }))], style: [{ selector: "node", style: { "background-color": "#0d1014", "border-color": "#42d9ef", "border-width": 2, color: "#f3f4ef", label: "data(label)", "font-size": 11, width: 58, height: 58, "text-valign": "bottom", "text-margin-y": 10 } }, { selector: "edge", style: { width: 1, "line-color": "#53616b", "target-arrow-color": "#42d9ef", "target-arrow-shape": "triangle", label: "data(label)", color: "#8d9aa3", "font-size": 8, "curve-style": "bezier" } }], layout: { name: "circle" } }); return () => instance.destroy(); }, [graph]); return <div className="graph-canvas" ref={ref}/>; }
function GraphView({ source, book }: { source: StudioDataSource; book: BookRecord }) { const data = useQuery({ queryKey: ["graph", book.id], queryFn: () => source.graph(book.id) }); return <section className="page"><PageHeader eyebrow="TRANSACTIONAL STORY STATE" title="Story graph" detail="Inspect entities, causal relationships, knowledge boundaries, clues, and unresolved promises."/>{data.data && <div className="graph-layout"><article className="panel span-2"><GraphCanvas graph={data.data}/></article><article className="panel"><PanelTitle index="O" title="OBLIGATION LEDGER"/><div className="obligation-list">{data.data.obligations.map((item) => <div key={item.id}><span className={`signal ${item.status === "open" ? "blocked" : "attention"}`}/><span><b>{item.title}</b><small>{item.kind} · chapter {item.target_chapter ?? "—"}</small></span></div>)}</div><PanelTitle index="C" title="CLUE COVERAGE"/><strong className="big-number">{data.data.clues.length}</strong><small>documented evidence records</small></article></div>}</section>; }

function Workflow({ source, book }: { source: StudioDataSource; book: BookRecord }) { const [jobId, setJobId] = useState<string>(); const detail = useQuery({ queryKey: ["job", jobId], queryFn: () => source.job(jobId!), enabled: Boolean(jobId), refetchInterval: 2_000 }); const run = useMutation({ mutationFn: () => source.startJob(book.id, 100), onSuccess: ({ id }) => setJobId(id) }); const nodes: Node[] = (detail.data?.nodes ?? ["research","outline","scene-plan","draft","validate","graph-update","audit","reader-panel","revise","approval"].map((node_key, i) => ({ id: node_key, node_key, kind: node_key, status: i === 0 ? "ready" : "pending", capability: "write", depends_on_json: "[]" }))).map((node, index) => ({ id: node.node_key, position: { x: (index % 5) * 190, y: Math.floor(index/5) * 150 }, data: { label: <div className="flow-node"><small>{String(index+1).padStart(2,"0")}</small><b>{node.kind.toUpperCase()}</b><span className={`node-status ${node.status}`}>{node.status}</span></div> }, className: `flow-${node.status}` })); const edges: Edge[] = nodes.slice(1).map((node, index) => ({ id: `e-${index}`, source: nodes[index]!.id, target: node.id, animated: detail.data?.nodes[index]?.status === "running" })); return <section className="page"><PageHeader eyebrow="SUPERVISED EXECUTION" title="DAG control room" detail="Typed nodes, explicit capabilities, durable state, and hard budget stops." action={<button className="button primary" onClick={() => run.mutate()} disabled={run.isPending}>RUN WORKFLOW</button>}/><div className="workflow-grid"><article className="panel flow-wrap"><ReactFlow nodes={nodes} edges={edges} fitView proOptions={{ hideAttribution: true }}><Background color="#28333a" gap={22}/><Controls/></ReactFlow></article><article className="panel"><PanelTitle index="L" title="EVENT LOG"/>{detail.data?.events.map((event) => <div className="log-line" key={event.id}><span className={`signal ${event.level === "warning" ? "attention" : "active"}`}/><code>{event.message}</code></div>) ?? <p className="empty-copy">Start a run to create a durable workflow record.</p>}{detail.data && <div className="budget"><span>RUN BUDGET</span><b>${(detail.data.job.used_cents/100).toFixed(2)} / ${(detail.data.job.budget_cents/100).toFixed(2)}</b><progress value={detail.data.job.used_cents} max={detail.data.job.budget_cents}/></div>}</article></div></section>; }

function Reviews({ source, book }: { source: StudioDataSource; book: BookRecord }) { const data = useQuery({ queryKey: ["reviews", book.id], queryFn: () => source.reviews(book.id) }); return <section className="page"><PageHeader eyebrow="AUTHOR DECISION QUEUE" title="Review center" detail="Agent findings are proposals. Canon-changing work remains yours to approve."/><div className="review-grid">{data.data?.map((review) => <article className={`review-card ${review.severity}`} key={review.id}><div><code>{review.source.toUpperCase()}</code><span className={`status ${review.status}`}>{review.status}</span></div><h2>{review.title}</h2><p>{review.detail}</p><footer><button className="button">REJECT</button><button className="button primary">APPROVE WITH RATIONALE</button></footer></article>)}{data.data?.length === 0 && <p>No pending reviews.</p>}</div></section>; }
function Exports({ source, book }: { source: StudioDataSource; book: BookRecord }) { const closure = useQuery({ queryKey: ["closure", book.id], queryFn: () => source.closure(book.id) }); const run = useMutation({ mutationFn: () => source.exportBook(book.id) }); return <section className="page"><PageHeader eyebrow="PUBLISHING READINESS" title="Export center" detail="Generate portable manuscript files with an auditable closure and citation record."/><div className="export-grid"><article className={`closure ${closure.data?.publishable ? "verified" : "blocked"}`}><span className="seal">{closure.data?.publishable ? "✓" : "!"}</span><div><p>PUBLICATION GATE</p><h2>{closure.data?.publishable ? "READY" : "BLOCKED"}</h2><small>{closure.data?.findings.length ?? 0} active finding(s)</small></div></article><article className="panel"><PanelTitle index="F" title="EXPORT BUNDLE"/><ul><li>manuscript.md</li><li>closure-report.json</li><li>book.json</li></ul><button className="button primary" disabled={!closure.data?.publishable || run.isPending} onClick={() => run.mutate()}>GENERATE EXPORT</button>{!closure.data?.publishable && <p className="error">Resolve critical findings before export.</p>}{run.data && <code>{run.data.outputDirectory}</code>}</article></div><div className="finding-list">{closure.data?.findings.map((finding) => <article key={finding.code + finding.entityId}><code>{finding.code}</code><p>{finding.message}</p><span>{finding.severity}</span></article>)}</div></section>; }

export function StudioApp({ dataSource, embedded = false }: { dataSource: StudioDataSource; embedded?: boolean }) { const Router = embedded ? MemoryRouter : BrowserRouter; return <QueryClientProvider client={queryClient}><Router><Frame source={dataSource}/></Router></QueryClientProvider>; }
